### PR TITLE
[perf] Remove Task Name

### PR DESCRIPTION
**Pull request by ppenna**
## Description

This PR removes tasks names from the Task structure to avoid memory allocations in the critical path.

### CODE REVIEW

**Review by iyzhang — APPROVED** [review]
Looks fine to me. We put these in in the first place so we could debug more easily. Is there some way to retain that functionality without the overhead?

**Comment by ppenna** [comment]
> Looks fine to me. We put these in in the first place so we could debug more easily. Is there some way to retain that functionality without the overhead?

Sure I fixed this. Task names will be compiled for debug builds.

**Comment by iyzhang** [comment]
Awesome, thanks for doing this.

**Review by iyzhang — APPROVED** [review]

**Comment by ppenna** [comment]
Closing this as requested by @iyzhang.

**Comment by iyzhang** [comment]
This was replaced in PR #1191

**Pull request closed without merging**
